import { useState } from "react";
import { useNavigate } from "react-router-dom";
import toast from "react-hot-toast";
import { CreditCard, PlusCircle } from "lucide-react";
import PageHeader from "../../components/PageHeader";
import { api, getErrorMessage } from "../../lib/api";

const blank = { role_title: "", required_skills: "", work_type: "Remote", commitment_level: "Part-time", deadline: "", description: "" };

export default function AddOpportunity() {
  const [form, setForm] = useState(blank); const [loading, setLoading] = useState(false); const navigate = useNavigate();
  const submit = async (event) => { event.preventDefault(); setLoading(true); try { await api.post("/founder/opportunities", form); toast.success("Opportunity published"); navigate("/dashboard/opportunities"); } catch (error) { if (error.response?.status === 402) { toast.error("Your first three opportunities are free. Upgrade to continue."); navigate("/dashboard/opportunities", { state: { premiumRequired: true } }); } else toast.error(getErrorMessage(error)); } finally { setLoading(false); } };
  return <><PageHeader eyebrow="Recruit your team" title="Publish an opportunity" description="Be precise about the role, required skills, working style, and the impact this person can make." /><form className="entity-form surface-card single" onSubmit={submit}><div className="form-grid"><label>Role title<input required minLength={2} value={form.role_title} onChange={(e) => setForm({ ...form, role_title: e.target.value })} placeholder="Frontend Engineer" /></label><label>Required skills <small>Comma separated</small><input required value={form.required_skills} onChange={(e) => setForm({ ...form, required_skills: e.target.value })} placeholder="React, JavaScript, REST API" /></label><label>Work type<select value={form.work_type} onChange={(e) => setForm({ ...form, work_type: e.target.value })}>{["Remote", "Hybrid", "On-site"].map((v) => <option key={v}>{v}</option>)}</select></label><label>Commitment level<select value={form.commitment_level} onChange={(e) => setForm({ ...form, commitment_level: e.target.value })}>{["Part-time", "Full-time", "Project-based", "Flexible"].map((v) => <option key={v}>{v}</option>)}</select></label><label>Application deadline<input type="date" required value={form.deadline} min={new Date(Date.now() + 86400000).toISOString().slice(0, 10)} onChange={(e) => setForm({ ...form, deadline: e.target.value })} /></label><label className="full-span">Role description<textarea required minLength={40} rows="8" value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} placeholder="Describe the responsibilities, collaboration style, current product stage, and what success looks like." /></label><div className="form-tip full-span"><CreditCard size={20} /><p>Founders can publish three opportunities free. A Stripe premium package unlocks unlimited posting for one year.</p></div><button className="button button-primary full-span" disabled={loading}><PlusCircle size={18} /> {loading ? "Publishing..." : "Publish opportunity"}</button></div></form></>;
}
